version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000' # for data access
      - '9001:9001' # for Minio console access
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=chunkfile-uploads

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local